#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG="/usr/bin/python3"
SCRIPT="/root/telegram-bot/inventory_bot.py"
WORKDIR="/root/telegram-bot"
LOGFILE="/root/inventory_bot.log"

start_service() {
    procd_open_instance
    procd_set_param command $PROG $SCRIPT
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param env PYTHONUNBUFFERED=1
    procd_set_param file $SCRIPT
    procd_set_param cwd $WORKDIR
    procd_close_instance
}

stop_service() {
    killall -q python3
}

