#!/bin/sh /etc/rc.common
#
# Init script untuk Packing List Bot di OpenWrt
# Copy file ini ke /etc/init.d/packing_list_bot
# Jalankan: chmod +x /etc/init.d/packing_list_bot
# Enable autostart: /etc/init.d/PL enable
#

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/python3
SCRIPT=/root/PL.py
PIDFILE=/var/run/packing_list_bot.pid

start_service() {
    procd_open_instance
    procd_set_param command $PROG $SCRIPT
    procd_set_param pidfile $PIDFILE
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    service_stop $PROG
}

restart() {
    stop
    sleep 2
    start
}