name: Auto Build IPK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d.%H%M')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build IPK
        run: |
          echo "2.0" > debian-binary

          mkdir control
          cat <<EOF > control/control
          Package: luci-app-statuswrtirfan
          Version: ${{ steps.version.outputs.VERSION }}
          Architecture: all
          Maintainer: Irfan
          Depends: luci, python3
          Description: StatusWRT Titanium Edition
          EOF

          tar -czf control.tar.gz control
          tar -czf data.tar.gz usr etc www

          tar -czf luci-app-statuswrtirfan_${{ steps.version.outputs.VERSION }}_all.ipk \
          debian-binary control.tar.gz data.tar.gz

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: StatusWRT v${{ steps.version.outputs.VERSION }}
          files: luci-app-statuswrtirfan_${{ steps.version.outputs.VERSION }}_all.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
